baseURL: "https://examplesite.com" #TODO
title: "@abhiyanbeta"
paginate: 5
theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto # Toggle dark/light based on browser
  disableThemeToggle: false # Hide theme toggle switch
  disableSpecial1stPost: false

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Abhiyan Bhandari"
    imageUrl: "https://avatars0.githubusercontent.com/u/57075221?s=460&v=4"

  socialIcons: # (not showing??)
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc" #TODO

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 1
    - name: Page1
      url: /page1/
      weight: 0
    - name: Page2
      url: /page2/
      weight: 0
    - name: Page3
      url: /page3/
      weight: 0
    - name: Page4
      url: /page4/
      weight: 0
